pre:
	@cd ../../project/packages/sh/;echo [sh] Running project Script...;sh pre.sh
build:
	@cd ../../project/packages/sh/;echo [sh] Running project Script...;sh build.sh
post:
	@cd ../../project/packages/sh/;echo [sh] Running project Script...;sh post.sh
