pre:
	@cd ../../project/packages/makefile/;echo [makefile] Running project Makefile...;make pre
build:
	@cd ../../project/packages/makefile/;echo [makefile] Running project Makefile...;make build
post:
	@cd ../../project/packages/makefile/;echo [makefile] Running project Makefile...;make post
