pre:
	@cd ../../project/packages/makefile/;echo [makefile] Running project Makefile...;make pre MAKRE_ROOT=$MAKRE_ROOT
build:
	@cd ../../project/packages/makefile/;echo [makefile] Running project Makefile...;make build MAKRE_ROOT=$MAKRE_ROOT
post:
	@cd ../../project/packages/makefile/;echo [makefile] Running project Makefile...;make post MAKRE_ROOT=$MAKRE_ROOT
install:
	@:
uninstall:
	@:
